import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, BriefcaseBusiness, Code2, FolderKanban, House, Info, Link, Mail, MapPin, Menu, Moon, Phone, Sparkles, Sun, UserRound, X } from 'lucide-react'
import data from '../data.json'
import { Badge, Button, Card, Tabs } from './components/ui'
import LiveBackground from './components/LiveBackground'

const nav = ['Home', 'About', 'Skills', 'Experience', 'Projects', 'Certifications']
const toId = label => label.toLowerCase()
const formatRoleDate = value => value.startsWith('2024') ? '2024' : value.replaceAll(' - ', '.')

function MobileTabs({ activeTab, onChange, moreOpen, setMoreOpen }) {
  const tabs = [[ 'home', 'Home', House ], [ 'about', 'About', Info ], [ 'skills', 'Skills', Sparkles ], [ 'experience', 'Work', UserRound ], [ 'projects', 'Projects', FolderKanban ]]
  return <><div className="mobile-tabs" role="tablist" aria-label="Portfolio sections">{tabs.map(([id, label, Icon]) => <button key={id} className={activeTab === id ? 'active' : ''} role="tab" aria-selected={activeTab === id} onClick={() => onChange(id)}><Icon size={19}/><span>{label}</span></button>)}<button className={moreOpen || activeTab === 'certifications' ? 'active' : ''} role="tab" aria-selected={moreOpen || activeTab === 'certifications'} onClick={() => setMoreOpen(true)}><Menu size={19}/><span>More</span></button></div>{moreOpen && <div className="more-sheet-backdrop" onClick={() => setMoreOpen(false)}><section className="more-sheet" role="dialog" aria-modal="true" aria-label="More sections" onClick={event => event.stopPropagation()}><div className="sheet-handle"/><p className="eyebrow">MORE</p><button onClick={() => { onChange('certifications'); setMoreOpen(false) }}>Certifications <span>→</span></button><button onClick={() => { onChange('home'); setMoreOpen(false) }}>Back to home <span>↑</span></button></section></div>}</>
}

function Header() {
  const [dark, setDark] = useState(() => localStorage.getItem('theme') !== 'light')
  const [open, setOpen] = useState(false)
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('theme', dark ? 'dark' : 'light') }, [dark])
  const scroll = item => { document.getElementById(toId(item))?.scrollIntoView({ behavior: 'smooth' }); setOpen(false) }
  return <header className="header"><a className="brand" href="#home" onClick={() => scroll('Home')}>JG<span>.</span></a><nav className={open ? 'nav open' : 'nav'}>{nav.map(item => <button key={item} onClick={() => scroll(item)}>{item}</button>)}</nav><div className="header-actions"><button className={`theme-switch ${dark ? 'is-dark' : ''}`} type="button" aria-label="Toggle theme" aria-pressed={dark} onClick={() => setDark(!dark)}><span className="theme-thumb"><Sun className="theme-sun" size={15}/><Moon className="theme-moon" size={14}/></span></button><Button className="menu" variant="ghost" aria-label="Toggle menu" onClick={() => setOpen(!open)}>{open ? <X size={20}/> : <Menu size={20}/>}</Button></div></header>
}

function SectionHeading({ eyebrow, title, detail }) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{detail && <p className="section-detail">{detail}</p>}</div> }

export default function App() {
  const { profile, skills, experience, projects, certifications = [] } = data
  const [filter, setFilter] = useState('All')
  const [activeMobileTab, setActiveMobileTab] = useState('home')
  const [moreOpen, setMoreOpen] = useState(false)
  const filters = ['All', ...Array.from(new Set(projects.flatMap(item => item.tech))).slice(0, 5)]
  const shownProjects = useMemo(() => filter === 'All' ? projects : projects.filter(item => item.tech.includes(filter)), [filter, projects])
  return <><LiveBackground /><Header /><main className={`mobile-active-${activeMobileTab}`}>
    <section id="home" className="hero mobile-panel mobile-home"><div className="hero-copy"><p className="eyebrow">IT SUPPORT · PHILIPPINES</p><h1>Reliable systems.<br/><em>Calmer teams.</em></h1><p className="lede">{profile.summary}</p><div className="actions"><a className="button button-default" href={`mailto:${profile.email}`}>Let’s talk <ArrowUpRight size={17}/></a><Button variant="outline" onClick={() => document.getElementById('projects').scrollIntoView({behavior:'smooth'})}>View selected work</Button></div></div><Card className="portrait-card"><div className="portrait-glow"/><img className="portrait-dark" src="/static/images/profile-portrait-theme-current.png" alt={`Portrait of ${profile.name}`}/><img className="portrait-light" src="/static/images/profile-portrait-light-theme.png" alt="" aria-hidden="true"/><div className="availability"><span className="status-dot"/> Available for opportunities</div></Card></section>
    <section className="contact-strip mobile-panel mobile-home" aria-label="Contact details"><a href={`mailto:${profile.email}`}><Mail/> <span><small>Email</small>{profile.email}</span></a><a href={`tel:${profile.phone.replace(/\s/g,'')}`}><Phone/> <span><small>Phone</small>{profile.phone}</span></a><span><MapPin/> <span><small>Location</small>{profile.location}</span></span><span className="socials"><a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Link/></a><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub"><Code2/></a></span></section>
    <section id="about" className="section about mobile-panel mobile-about"><SectionHeading eyebrow="01 / ABOUT" title="The person behind the support."/><div className="about-grid"><p>I turn complex infrastructure into reliable, day-to-day operations. My approach is practical: resolve the immediate issue, then build the process and documentation that keeps it from coming back.</p><div className="role-list">{profile.target_roles.map(role => <div key={role}><span>✦</span>{role}</div>)}</div></div></section>
    <section id="skills" className="section mobile-panel mobile-skills"><SectionHeading eyebrow="02 / CAPABILITIES" title="Tools I use to keep work moving."/><div className="skills-grid">{skills.map((skill, i) => <Card key={skill.name} className="skill-card"><div className="skill-face skill-front"><span className="skill-number">{String(i + 1).padStart(2,'0')}</span><div><h3>{skill.name}</h3><p>{skill.evidence}</p><div className="skill-foot"><Badge>{skill.level}</Badge><span>Used {skill.last_used}</span></div></div></div><div className="skill-face skill-back"><span className="skill-number">CAPABILITY {String(i + 1).padStart(2,'0')}</span><h3>{skill.name}</h3><p>{skill.evidence}</p><div className="skill-back-meta"><Badge>{skill.level}</Badge><span>Last used {skill.last_used}</span></div></div></Card>)}</div></section>
    <section id="experience" className="section mobile-panel mobile-experience"><SectionHeading eyebrow="03 / EXPERIENCE" title="Where I’ve made an impact." detail={`${experience.length} role${experience.length === 1 ? '' : 's'}`}/><div className="timeline">{experience.map(role => <Card className="role-card" key={`${role.company}${role.role}`}><div className="role-header"><div><h3>{role.role}</h3><p>{role.company} · {role.location}</p></div><Badge>{formatRoleDate(role.start)} – {(role.end || 'PRESENT').toUpperCase()}</Badge></div><ul>{role.achievements.map(item => <li key={item}>{item}</li>)}</ul><div className="tag-list">{role.tech.map(tech => <Badge key={tech}>{tech}</Badge>)}</div></Card>)}</div></section>
    <section id="projects" className="section mobile-panel mobile-projects"><SectionHeading eyebrow="04 / SELECTED WORK" title="Projects with practical outcomes." detail={`${projects.length} projects`}/><Tabs tabs={filters} value={filter} onChange={setFilter}/><div className="projects-grid">{shownProjects.map(project => <Card className="project-card" key={project.title}><div className="project-top"><span className="project-icon"><BriefcaseBusiness size={19}/></span><span>{project.date}</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="impact"><strong>Impact</strong>{project.impact}</div><div className="tag-list">{project.tech.map(tech => <Badge key={tech}>{tech}</Badge>)}</div></Card>)}</div></section>
    <section id="certifications" className="section mobile-panel mobile-certifications"><SectionHeading eyebrow="05 / CREDENTIALS" title="Learning, on purpose."/><div className="cert-grid">{certifications.length ? certifications.map(c => <Card key={c.name}><h3>{c.name}</h3><p>{c.issuer}</p></Card>) : <Card className="empty"><p>Certifications are being curated. In the meantime, explore the experience and project work above.</p></Card>}</div></section>
    <section className="cta mobile-panel mobile-home"><p className="eyebrow">GET IN TOUCH</p><h2>Let’s make technology<br/><em>feel dependable.</em></h2><a className="button button-light" href={`mailto:${profile.email}?subject=${encodeURIComponent('Portfolio enquiry')}`}>Send an email <Mail size={17}/></a></section>
  </main><footer><span>© {new Date().getFullYear()} {profile.name}</span><a href="#home">Back to top ↑</a></footer><MobileTabs activeTab={activeMobileTab} onChange={setActiveMobileTab} moreOpen={moreOpen} setMoreOpen={setMoreOpen}/></>
}
